# Generated by Django 4.1.1 on 2022-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=14, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=14, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=14, verbose_name='Telefon')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('tarix', models.DateTimeField(verbose_name='Tarix')),
            ],
        ),
    ]
