# Generated by Django 4.1.1 on 2022-10-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=14, verbose_name='brend')),
                ('image', models.FileField(default='https://archive.org/download/no-photo-available/no-photo-available.png', upload_to='images')),
                ('data_brend', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=14, verbose_name='ad')),
                ('imageclient', models.FileField(default='https://archive.org/download/no-photo-available/no-photo-available.png', upload_to='images')),
                ('soyad', models.CharField(max_length=20, verbose_name='soyad')),
                ('tel', models.CharField(max_length=20, verbose_name='tel')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('shirket', models.CharField(max_length=35, verbose_name='shirket')),
                ('data_client', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xerc', models.IntegerField(verbose_name='xerc')),
                ('data_xerc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmiqdar', models.IntegerField(verbose_name='pmiqdar')),
                ('data_order', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul', models.CharField(max_length=35, verbose_name='mehsul')),
                ('alis', models.IntegerField(verbose_name='alis')),
                ('satis', models.IntegerField(verbose_name='satis')),
                ('miqdar', models.IntegerField(verbose_name='miqdar')),
                ('data_product', models.DateTimeField(auto_now_add=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
