# Generated by Django 4.1.1 on 2022-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brands_clients_expenses_orders_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imageproduct',
            field=models.FileField(default='https://archive.org/download/no-photo-available/no-photo-available.png', upload_to='images'),
        ),
    ]
