# Generated by Django 4.1.1 on 2022-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_imageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tesdiq',
            field=models.IntegerField(default=0, verbose_name='tesdiq'),
        ),
    ]
