# Generated by Django 4.1.1 on 2022-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ishciler_alter_orders_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='ishciler',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='products',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='user_id'),
        ),
    ]
