# Generated by Django 4.1.1 on 2022-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_brands_user_id_clients_user_id_expenses_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senedler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ishci_id', models.IntegerField(max_length=35, verbose_name='ishci_id')),
                ('basliq', models.CharField(max_length=35, verbose_name='basliq')),
                ('skan', models.FileField(default='https://archive.org/download/no-photo-available/no-photo-available.png', upload_to='images')),
                ('qeyd', models.CharField(max_length=35, verbose_name='qeyd')),
                ('data_senedler', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
